LightYear.ColdChainDelivery.WebSite/Controllers/LogisticsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using LightYear.ColdChainDelivery.BL.BE.Account;
using LightYear.ColdChainDelivery.BL.Services.Account;
using LightYear.ColdChainDelivery.BL.Services.Logistics;
using LightYear.ColdChainDelivery.DA.ColdChainDeliveryDb;
using LightYear.ColdChainDelivery.DA.ColdChainDeliveryDbReadOnly;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace LightYear.ColdChainDelivery.WebSite.Controllers
{
    public class LogisticsController : Controller
    {
        public ILogisticsService LogisticsService { get; set; }
        private readonly IConfiguration Configuration;
        IAccountService AccountService { get; set; }

        public LogisticsController(ILogisticsService logisticsService, IConfiguration configuration, IAccountService accountService)
        {
            LogisticsService = logisticsService;
            Configuration = configuration;
            AccountService = accountService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetLogistics()
        {
            var data = LogisticsService.GetLogistics();
            var output = JsonConvert.SerializeObject(data);
            return Content(output);
        }

        public IActionResult GetActiveLogistics()
        {
            List<DA.ColdChainDeliveryDbReadOnly.Logistic> data = LogisticsService.GetLogistics().Where(a => a.Active.Equals(1)).ToList();

            var claim = HttpContext.User.Claims.FirstOrDefault(a => a.Type == "UserInfo");

            if (claim != null)
            {
                var userInfoString = claim.Value;
                UserInfoEntity userInfoEntity = JsonConvert.DeserializeObject<UserInfoEntity>(userInfoString);
                var member = AccountService.GetMember(userInfoEntity.Id);
                var name = LogisticsService.GetLogisticById(member.LogisticsId ?? 0);
                if (name != null)
                    data = data.Where(a => a.Id.Equals(member.LogisticsId ?? 0)).ToList();
            }
            return Json(data);
        }

        public async Task<IActionResult> Insert (DA.ColdChainDeliveryDb.Logistic logistic, IFormFile file)
        {
            string fullPath = "";

            if (file != null && file.Length > 0)
            {
                var savePath = Configuration.GetValue<string>("UploadLogo");

                string uniqueFileName = LogisticsService.GetUniqueFileName(file.FileName);

                fullPath = string.Format("{0}/{1}", savePath, uniqueFileName);

                using (FileStream stream = new FileStream(fullPath, FileMode.Append))
                {
                    await file.CopyToAsync(stream);
                }
            }

            if (logistic.Id > 1) // update
            {
                if(!string.IsNullOrEmpty(fullPath))
                    logistic.Logo = fullPath.Substring(7);
                LogisticsService.Update(logistic);
            }
            else //insert
            {
                logistic.Logo = fullPath.Substring(7);
                var id = LogisticsService.Insert(logistic);
                logistic.Id = id;
            }

            return View("index");
        }

        public IActionResult FakeDelete(string json)
        {
            List<DA.ColdChainDeliveryDb.Logistic> logistic = JsonConvert.DeserializeObject<List<DA.ColdChainDeliveryDb.Logistic>>(json);
            LogisticsService.FakeDelete(logistic[0]);
            var output = JsonConvert.SerializeObject(logistic[0]);
            return Content(output);
        }
    }
}

LightYear.ColdChainDelivery.WebSite/Views/Logistics/Index.cshtml
@{
    ViewData["Title"] = "物流商管理";
    Layout = "~/Views/Shared/_LayoutTestForKendo.cshtml";
}

    <div>
        <h1>物流商管理</h1>
        <div class="demo-section k-content" style="display:none;" id="form">
            <form method="post" enctype="multipart/form-data" asp-controller="Logistics" asp-action="Insert">

                    <input type="file" accept=".jpg,.png" name="file"  />
                    <p>
                        <input type="hidden" id="Id" name="Id" />
                    </p>
                    <p>
                        <label>物流商:<input type="text" id="Company" name="Company" /></label>
                    </p>
                    <p>
                        <label>物流商代碼:<input type="text" id="CompanyCode" name="CompanyCode" /></label>
                    </p>
                    <p>
                        <label>狀態:</label>
                        <input id="Active_true" name="Active" value=1 type="radio" checked="" />啟用
                        <input id="Active_false" name="Active" value=0 type="radio" checked="" />停用
                    </p>
                    <button id="submit" class="btn btn-warning"><i class="fa fa-upload"></i>儲存</button>
            </form>
        </div>
        <div id="grid"></div>
    </div>

<script>

    dataSource = new kendo.data.DataSource({
        transport: {
            read: {
                url: "GetLogistics",
                dataType: "json"
            },
            parameterMap: function (options, operation) {
                if (operation !== "read" && options.models) {
                    return { json: kendo.stringify(options.models) };
                }
            },
        },
        batch: true,
        pageSize: 30,
        schema: {
            model: {
                id: "Id",
                fields: {
                    Id: { editable: false, nullable: false, defaultValue: 0 },
                    Company: { validation: { required: true } },
                    CompanyCode: { validation: { required: true } },
                    Logo: { validation: { required: true } },
                    Active: { type: "number" },
                }
            }
        }
    });

    $("#grid").kendoGrid({
        dataSource: dataSource,
        sortable: true,
        filterable: true,
        pageable: true,
        height: 550,
        toolbar: [{ template: '<button id="export" class="k-button" onclick="file()">新增物流商</button> <button style="display:none;" id="cancel" class="k-button" onclick="fileClose()">取消</button>' }],
        columns: [
            { hidden: true, field: "Id", title: "序號", width: "100px" },
            { field: "Company", title: "物流商" },
            { field: "CompanyCode", title: "物流商代碼" },
            {
                field: "Logo", title: "Logo", template: "<div class='customer-photo'" +
                    "style='background-image: url(\"#: Logo #\");'></div>"
            },
            { field: "Active", title: "狀態", template: "<label>#:Active == 1 ? '啟用':'停用'#</label>" },
            { command: [{ text: "編輯", click: customEdit }, { text: "取消", click: fileClose }], title: "&nbsp;" }
        ],
    });

    function file() {
        $("#form").show();
        $("#cancel").show();
    }

    function fileClose() {
        $("#form").hide();
    }

    function customEdit(e) {
         e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        $("#form").show();
        $("#Id").val(dataItem.Id);
        $("#Company").val(dataItem.Company);
        $("#CompanyCode").val(dataItem.CompanyCode);

        if (dataItem.Active == 1) {
            $("#Active_true").prop('checked', true);
        } else {
            $("#Active_false").prop('checked', true);
        }
    }

</script>

<style type="text/css">
    .customer-photo {
        display: inline-block;
        width: 50px;
        height: 50px;
        border-radius: 50%;
        background-size: 42px 45px;
        background-position: center center;
        vertical-align: middle;
        line-height: 32px;
        box-shadow: inset 0 0 1px #999, inset 0 0 10px rgba(0,0,0,.2);
        margin-left: 5px;
    }
</style>